version: '3.8'

services:
  api-gateway:
    image: nginx:1.18-alpine
    working_dir: /var/www/html/
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./apiGateway/nginx.conf:/etc/nginx/conf.d/default.conf

# Auth Service
  auth-service:
    # image: node:14
    build:
      context: ./authService
      dockerfile: Dockerfile
      target: base
    working_dir: /app
    depends_on: 
      - api-gateway
      - auth-service-db
    volumes:
      - ./authService:/app
    command: 'npm start'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports: 
      - '4000:4000'


  auth-service-db:
    image: mongo
    volumes:
      - mongo:/data/db
    ports: 
      - '27017:27017'

# XXX Service

# Volumes
volumes:
  mongo: